name: Update README with Latest Repo

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch latest repo
        run: |
          LATEST_REPO=$(curl -s https://api.github.com/users/YazRaso/repos?sort=updated | jq -r '.[0].name')
          sed -i '/<!--latest-project-->/c\[Check out my latest project](https://github.com/YazRaso/'"$LATEST_REPO"') README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git commit -am "Update latest project link" && git push)
